### ISSUE TITLE
please guide as to if it works or not and how

### ISSUE THREAD

**Issue by ghost** [Project-Mushroom/platform_packages_apps_Dialer#1]

**Comment by AmeChanRain** [comment]
You need to add an overlay on your device configuration to enable Call Record function, check this commit. https://github.com/Miku-UI-Devices/Miku_device_essential_mata/commit/47def4db39a31dd76fb6fdcbe7f2d4d7f30ee07e

**Comment by ReallySnow** [comment]
You should make it clear what you want to make effective

**Comment by ghost** [comment]
> You should make it clear what you want to make effective

Oh right
I use lavender(rn7) a12 rooted
But can't get call recording in Google dialler
I tried many methods

I think editing it in mt manager might help but what to change in it, or is there a module to do that

**Comment by ghost** [comment]
> You need to add an overlay on your device configuration to enable Call Record function, check this commit. [Miku-UI-Devices/Miku_device_essential_mata@47def4d](https://github.com/Miku-UI-Devices/Miku_device_essential_mata/commit/47def4db39a31dd76fb6fdcbe7f2d4d7f30ee07e)

Can i do this in my phone custom ROM from mt manager(root browser)

**Comment by ghost** [comment]
If yes then how
Explain if possible
Thankyou

**Comment by ghost** [comment]
Also if you don't mind
What is this repo for😅
